# WordPress development environment
services:
  wordpress:
    image: wordpress:latest
    container_name: wp-dev
    ports:
      - "5000:80"
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_ADMIN_USER: admin
      WORDPRESS_ADMIN_PASSWORD: D@wordpresska79823!4
      WORDPRESS_ADMIN_EMAIL: endersclarity@gmail.com
      WP_ENVIRONMENT_TYPE: development
    volumes:
      - wp_data:/var/www/html
      - ./wp-content:/var/www/html/wp-content
    depends_on:
      - mysql
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    container_name: wp-mysql
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  wp_data:
  mysql_data: